# Generated by Django 6.0.7 on 2026-07-09 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("is_retry", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=10,
                    ),
                ),
                ("response_code", models.CharField(max_length=50)),
                ("response_message", models.TextField()),
                ("duration_ms", models.PositiveIntegerField()),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt_number"],
                "indexes": [
                    models.Index(
                        fields=["payment"], name="payments_pa_payment_d81a1c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_pa_status_307c59_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment", "attempt_number"),
                        name="unique_payment_attempt_number",
                    )
                ],
            },
        ),
    ]
