services:
  web:
    build: .
    command: /app/deploy/start-web.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

  worker:
    build: .
    command: /app/deploy/start-worker.sh
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  beat:
    build: .
    command: /app/deploy/start-beat.sh
    env_file:
      - .env
    volumes:
      - ./src:/app/src