services:
  web:
    build: .
    container_name: payment_retry_web

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - ./src:/app/src

    ports:
      - "8000:8000"

    env_file:
      - .env.example

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: payment_retry_db

    restart: always

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: